#!/bin/bash

# Copyright © 2018-2023 InAccel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ ${DEBUG} ] && set -vx
set -eu

rootless() {
	[ "$(id -u 2>/dev/null)" != "0" ]
}

if rootless; then
	: ${INACCEL_RUNTIMES:=${XDG_CONFIG_HOME:-~/.config}/inaccel/runtimes}
else
	: ${INACCEL_RUNTIMES:=/etc/inaccel/runtimes}
fi

mkdir -p ${INACCEL_RUNTIMES}

curl -sSL "https://releases.inaccel.com/api?repo=runtime&tag=fpga-${*:-*}" | tar xz -C ${INACCEL_RUNTIMES}

(cd ${INACCEL_RUNTIMES} && echo ${INACCEL_RUNTIMES}: *-fpga)
