#!/bin/bash

# Copyright © 2018-2023 InAccel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[ ${DEBUG} ] && set -vx
set -eu

rootless() {
	[ "$(id -u 2>/dev/null)" != "0" ]
}

if rootless; then
	: ${INACCEL_RUNTIMES:=${XDG_CONFIG_HOME:-~/.config}/inaccel/runtimes}
else
	: ${INACCEL_RUNTIMES:=/etc/inaccel/runtimes}
fi

cp ${INACCEL_RUNTIMES}/intel-fpga/inaccel.pc ${INACCEL_RUNTIMES}/intel-fpga/.inaccel.pc.swp
trap "rm ${INACCEL_RUNTIMES}/intel-fpga/.inaccel.pc.swp" EXIT
i=1
for library in alteracl intel_opae_mmd opae-u opae-v xfpga; do
	echo Locating ${library} library...
	paths=$(locate -e lib${library}.so || :)
	if [ -z "${paths}" ]; then
		>&2 echo Error: Unable to locate lib${library}.so
	else
		n=$(wc -w <<< ${paths})
		if [ ${n} == "1" ]; then
			dir=$(dirname ${paths})
		else
			PS3="Please select a path [1-${n}]: "
			select path in ${paths}; do
				if [ ! -z ${path} ]; then
					dir=$(dirname ${path})
					break
				fi
			done
		fi
		sed -zi "s|-L\S*|-L${dir}|${i}" ${INACCEL_RUNTIMES}/intel-fpga/.inaccel.pc.swp
		sed -i "/-l${library}/s|^#||" ${INACCEL_RUNTIMES}/intel-fpga/.inaccel.pc.swp
	fi
	echo ---
	let i+=1
done
echo ${INACCEL_RUNTIMES}/intel-fpga/inaccel.pc:
if diff -s ${INACCEL_RUNTIMES}/intel-fpga/inaccel.pc ${INACCEL_RUNTIMES}/intel-fpga/.inaccel.pc.swp | grep -e "<" -e ">"; then
	cp ${INACCEL_RUNTIMES}/intel-fpga/.inaccel.pc.swp ${INACCEL_RUNTIMES}/intel-fpga/inaccel.pc
else
	echo No changes made
fi
